version: '3.3'
services:
  database:
    image: mysql
    command: --lower_case_table_names=2
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '5306:3306'
